[package]
name = "boa_utils"
keywords = ["javascript", "js", "string"]
categories = ["parser-implementations", "compilers"]
readme = "../../README.md"
description.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
sptr = "0.3.2"

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
